### ISSUE TITLE
Possible bug in Open Liberty : java.io.FileNotFoundException: JAR entry com/jcraft/jsch/jce/SignatureEdDSA.class not found after upgrading to Java 17 and Open Liberty 24.0.0.12

### ISSUE THREAD

**Issue by Ssoli** [OpenLiberty/open-liberty#30529]
**Describe the bug** 
After upgrading our application from Java 11 to Java 17 and from JavaEE 8 to Jakarta 10, and running on Open Liberty 24.0.0.12, we are encountering the following error during startup:

> `java.io.FileNotFoundException: JAR entry com/jcraft/jsch/jce/SignatureEdDSA.class not found in /path/to/liberty/server/lib/jsch-0.2.21.jar`

This error occurs specifically during the startup of the Open Liberty server when trying to initialize a class from the JSch library.

**Environment:**
- Java Version: 17
- Open Liberty Version: 24.0.0.12
- Liberty Maven Plugin Version: 3.11.0
- JSch Version: 0.2.21 (we are using this version as it is bundled with our Liberty runtime, but we are also trying a custom version of JSch, I tested 0.2.22 as well but encountered same problem)

**Problem:**
The specific error indicates that the class com.jcraft.jsch.jce.SignatureEdDSA is missing from the JAR file jsch-0.2.21.jar, even though the class should be part of the JSch library according to the documentation.

> `[2025-01-10T10:20:43.573+0100] 0000002d com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.io.FileNotFoundException: JAR entry com/jcraft/jsch/jce/SignatureEdDSA.class not found in /path/to/liberty/server/lib/jsch-0.2.21.jar`

Despite using the correct JSch version (0.2.21), the server cannot find the required SignatureEdDSA.class file in the JAR, which seems to indicate an issue with the JAR itself or its compatibility with the newer Java versions.

**Steps to Reproduce:**
1. Upgrade from Java 11 to Java 17.
2. Upgrade from JavaEE 8 to Jakarta 10.
3. Use Open Liberty version 24.0.0.12.
4. Deploy the application with the bundled JSch library (0.2.21).
5. Start the Liberty server.

**Expected Behavior:**
The server should start without issues, loading SignatureEdDSA.class from the JSch JAR.

**Actual Behavior:**
The server throws a FileNotFoundException, indicating that the SignatureEdDSA.class file is missing from the JAR.

**Additional Context**:
We have tried including a newer version of JSch (e.g., mwiede/jsch), but the issue persists.
We are using the Liberty Maven Plugin to deploy the application, with dependencies copied as part of the configuration.

**Questions:**
- Is there a known compatibility issue between Open Liberty 24.0.0.12 and JSch 0.2.21?
- Could this be related to the way Open Liberty loads classes or its classpath configuration?
- You can find the relevant information in this comment on GitHub: [MWiede's response](https://github.com/mwiede/jsch/issues/744#issuecomment-2582705062) where they addressed a similar question. It offers insights on handling the issue you are experiencing.

**Comment by tjwatson** [comment]
@Ssoli thanks for the report.  I will take a look at the MR Jar support in Liberty.  I suspect JSch code must be trying to get access to the class resource with a URL and that URL is not correctly connecting to the MR version path of that class in the MR JAR.

**Comment by norrisjeremy** [comment]
> [@Ssoli](https://github.com/Ssoli) thanks for the report. I will take a look at the MR Jar support in Liberty. I suspect JSch code must be trying to get access to the class resource with a URL and that URL is not correctly connecting to the MR version path of that class in the MR JAR.

@tjwatson I am one of the co-maintainers of JSch and it does not attempt load any sort of resource from a URL as you have described.

**Comment by norrisjeremy** [comment]
> > [@Ssoli](https://github.com/Ssoli) thanks for the report. I will take a look at the MR Jar support in Liberty. I suspect JSch code must be trying to get access to the class resource with a URL and that URL is not correctly connecting to the MR version path of that class in the MR JAR.
> 
> [@tjwatson](https://github.com/tjwatson) I am one of the co-maintainers of JSch and it does not attempt load any sort of resource from a URL as you have described.

To elaborate further, the only thing JSch does is use standard reflection API's, such as `Class.forName(...)`, which are not passed URLs, but instead are simply class names such as `com.jcraft.jsch.jce.SignatureEd25519`.

**Comment by tjwatson** [comment]
The error message is coming from one of these two places:

https://github.com/OpenLiberty/open-liberty/blob/9d0d20173b90d296667106ab873a54d1cbd5f3c4/dev/com.ibm.ws.artifact.url/src/com/ibm/ws/artifact/url/internal/WSJarURLStreamHandler.java#L270

https://github.com/OpenLiberty/open-liberty/blob/9d0d20173b90d296667106ab873a54d1cbd5f3c4/dev/com.ibm.ws.artifact.url/src/com/ibm/ws/artifact/url/internal/WSJarURLStreamHandler.java#L232

That indicates that something is getting the URL for the class resource and either calling `connect` or `getInputStream` on the URL to the class resource.

I've been able to reproduce the issue with my own MR JAR testcase.

**Comment by Ssoli** [comment]
@tjwatson I am wondering when is the plan of above fix?

**Comment by tjwatson** [comment]
> [@tjwatson](https://github.com/tjwatson) I am wondering when is the plan of above fix?

I just merged a fix for the issue.  That should get into a [nightly](https://openliberty.io/start/#development_builds) build soon.  It would be great if you could try out the nightly build once this makes it into a build.  Note that it may be a day or two before it gets into the nightly build depending on how fast our `integration` branch gets merged into the `release` branch.  I will try to remind you once I see this fix get into `release`.

**Comment by tjwatson** [comment]
@Ssoli PR #30563 is now in the `release` branch and our nightly developer builds should have the fix.  Could you try out the latest nightly [developer build](https://openliberty.io/start/#development_builds) to see if it addresses your issue?

**Comment by JoshDM** [comment]
Unrelated to OP, one of my teammates just hit me up asking about this exact bug after the first deploy of his jsch app on OpenLiberty 24.0.0.2 and I see you're in the actual midst of fixing this with a dev comment 15 minutes ago. Wild.

**Comment by Ssoli** [comment]
Hi @tjwatson,

Thanks for fixing it quickly. We have now tested again but are still encountering the error.

Here’s what we have done:

1. In our runtime `pom.xml` file, we added the following plugin:

```
<build>
    <plugins>
        <plugin>
            <groupId>io.openliberty.tools</groupId>
            <artifactId>liberty-maven-plugin</artifactId>
            <configuration>
                <!--<libertyRuntimeVersion>${liberty-version}</libertyRuntimeVersion>-->
                <runtimeArtifact>
                    <groupId>io.openliberty.beta</groupId>
                    <artifactId>openliberty-runtime</artifactId>
                    <version>25.0.0.2-beta</version>
                    <type>zip</type>
                </runtimeArtifact>
               .....
            </configuration>
        </plugin>
    </plugins>
</build>
```
2. We built and started the server. Here are some relevant logs:
```
********************************************************************************
Product = Open Liberty 25.0.0.2-beta (wlp-1.0.97.cl250120250113-0302)  
wlp.install.dir = [path]/[runtime]/zip/target/liberty/wlp/  
java.home = [path]\java\zulu17.52.17\zulu-jdk17.0.12  
java.version = 17.0.12  
java.runtime = OpenJDK Runtime Environment (17.0.12+7-LTS)  
os = Windows 10 (10.0; amd64) (en_US)  
process = 12345@xxxxx 
********************************************************************************
```
3. However, we encountered the following exception during startup:
```
------Start of DE processing------ = 
[2025-02-04T15:59:47.448+0100]  

Exception: java.io.FileNotFoundException  
Source: com.ibm.ws.annocache.classsource.internal.ClassSourceImpl_ClassLoader  
probeid: 179  

Stack Trace:  
java.io.FileNotFoundException: JAR entry com/jcraft/jsch/jce/SignatureEdDSA.class not found in  
/[path]/target/liberty/wlp/usr/servers/[runtime]/workarea/org.eclipse.osgi/60/data/cache/com.ibm.ws.app.manager_0/.cache/WEB-INF/lib/jsch-0.2.21.jar  

    at com.ibm.ws.artifact.url.internal.WSJarURLStreamHandler$WSJarURLConnectionImpl.getInputStreamInternal(WSJarURLStreamHandler.java:270)  
    at com.ibm.ws.artifact.url.internal.WSJarURLStreamHandler$WSJarURLConnectionImpl.getInputStream(WSJarURLStreamHandler.java:251)  
    at java.base/java.net.URL.openStream(URL.java:1161)  
    at com.ibm.ws.annocache.classsource.internal.ClassSourceImpl_ClassLoader.openResourceStream(ClassSourceImpl_ClassLoader.java:177)  
    at com.ibm.ws.annocache.classsource.internal.ClassSourceImpl.openResourceStream(ClassSourceImpl.java:481)  
    ...  

```

It seems like the server still is unable to find SignatureEdDSA.class in jsch-0.2.21.jar.

Have we performed the test correctly? Let us know if you need any additional details.

**Comment by tjwatson** [comment]
> Have we performed the test correctly? Let us know if you need any additional details.

Unfortunately we do not publish our nightly developer builds to maven central so it is not easy to test it with maven.  The fix is not in the `25.0.0.2-beta` release.  It will be included in the next release `25.0.0.2` and the `25.0.0.3-beta`.  To test this you would have to deploy your application "manually" to an install of one of our nightly developer builds.  For example: https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2025-02-04_0303/openliberty-all-25.0.0.2-cl250220250204-0303.zip

Alternatively, if you have a sample application I can try then push it up to your github fork and I can try it out myself.

**Comment by Ssoli** [comment]
> > Have we performed the test correctly? Let us know if you need any additional details.
> 
> Unfortunately we do not publish our nightly developer builds to maven central so it is not easy to test it with maven. The fix is not in the `25.0.0.2-beta` release. It will be included in the next release `25.0.0.2` and the `25.0.0.3-beta`. To test this you would have to deploy your application "manually" to an install of one of our nightly developer builds. For example: https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2025-02-04_0303/openliberty-all-25.0.0.2-cl250220250204-0303.zip
> 
> Alternatively, if you have a sample application I can try then push it up to your github fork and I can try it out myself.

Thanks for quick reply. It works better now. It is just to wait for stable release of 25.0.0.2.

**Comment by tjwatson** [comment]
> Thanks for quick reply. It works better now. It is just to wait for stable release of 25.0.0.2.

We appreciate you taking the time to confirm it is working in our developer builds before we have the final release for 25.0.0.2.  Thanks!

**Comment by tjwatson** [comment]
Closing this as fixed, it will be in the next release of Open Liberty (`25.0.0.2` and `25.0.0.3-beta`)

**Comment by Ssoli** [comment]
Hello @tjwatson, I am wondering when are you going to do the release 25.0.0.2?

**Comment by tjwatson** [comment]
> Hello [@tjwatson](https://github.com/tjwatson), I am wondering when are you going to do the release 25.0.0.2?

The release for `25.0.0.2` should be available very soon if not already available.
